global:
  scrape_interval: 5s
  evaluation_interval: 10s
  external_labels:
    cluster: mlops-lel
    env: local

scrape_configs:
  - job_name: ml-api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]
        labels:
          service: wine-classifier

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
